export const PaymentActionTypes = {
   SET_CURRENT_PAYMENT: 'SET_CURRENT_PAYMENT',


   PAYMENT_START: 'PAYMENT_START',
   PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
   PAYMENT_FAILURE: 'PAYMENT_FAILURE'
};